name: core
description: "Project core module"
version: 0.0.1
publish_to: "none"

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  firebase_core: ^2.14.0
  flutter_bloc: ^8.1.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.5
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.0.0
  connectivity_plus: ^4.0.1
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.0
  firebase_messaging: ^14.7.5
  flutter_svg: ^2.0.7
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: